c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
c_stdlib_version:              # [unix]
  - 2.17                       # [linux]
  - 11.0                       # [osx]
python:
  - 3.10
  - 3.11
  - 3.12
packages:
  - numpy
