c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
c_stdlib_version:              # [unix]
  - 2.17                       # [linux]
  - 11.0                       # [osx]  

libtorch:
  - 2.2.2
  - 2.3.0
  - 2.4.0
  - 2.5.0

cudatoolkit:
  - 11.8
  - 12.1
  - 12.1
  - 12.1

zip_keys:
  - libtorch
  - cudatoolkit
