c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
c_stdlib_version:              # [unix]
  - 2.17                       # [linux]
  - 11.0                       # [osx]  

root:
  - 6.32
#  - 6.34 # requires GCC 15

libtorch:
  - 2.6.0
#  - 2.8.0 # not ready yet

zip_keys:
  - libtorch
  - root
