c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
c_stdlib_version:              # [unix]
  - 2.17                       # [linux]
  - 11.0                       # [osx]  

root:
  - 6.32
  # - 6.34

libtorch:
  - 2.6.0
  # - 2.8.0 # not published yet for amd64.

zip_keys:
  - libtorch
  - root
