c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
c_stdlib_version:              # [unix]
  - 2.17                       # [linux]
  - 11.0                       # [osx]  

libtorch:
  - 2.1.2
  - 2.3.1
  - 2.5.1
  - 2.6.0
  - 2.7.0
