{% set versions = {
    "1.0.0": "99a9ae2fc8b9a1798666f9f32f0c0debe7372aa9",
} %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "root-plus")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  git_url: "https://git.ligo.org/kagra/libraries-addons/root/root-plus"
  git_rev: {{ version }}

requirements:
  build:
    - {{ compiler('cxx') }} # [linux]
    - {{ compiler('c') }}   # [linux]
    - {{ stdlib('c') }}

    - clang
    - cmake
    - make

    - cuda-nvcc

  host:
    - root
    - libarchive
    - howardhinnant_date
    - tbb-devel
    - libcurl

    - libtorch
    - cudatoolkit
    
    - libdate-tz
    - onnxruntime-cpp

  run:
    - root
    - libarchive
    - howardhinnant_date
    - tbb-devel
    - libcurl

    - libtorch
    - cudatoolkit
    
    - libdate-tz
    - onnxruntime-cpp

about:
  home: "https://git.ligo.org/kagra/libraries-addons/root/root-plus"
  license: "GPL-3.0"
  summary: "ROOT+ for Tensor Calculation & Advanced Signal Processing"
  description: |
    ROOT+ is an Open-Source library implementing complex tensor calculation, advanced signal processing. It can be used for scientific Machine Learning developments in C/C++"

extra:
  recipe-maintainers:
    - meiyasan
