{% set versions = {
    "beta": "769e2e2a14d315b01d8ee7dea5630223111caa42",
    "alpha": "be02f507e90727eaa5134f9ccea6c75dbb17d813",
} %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "root-plus")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  git_url: "https://git.ligo.org/kagra/libraries-addons/root/root-plus"
  git_rev: {{ version }}

requirements:
  build:
    - {{ compiler('cxx') }} # [linux]
    - {{ compiler('c') }}   # [linux]
    - {{ stdlib('c') }}

    - clang
    - cmake
    - make

    - cuda-nvcc

  host:
    - root
    - minio-cpp=latest
    - libdate-tz
    - libarchive
    - onnxruntime-cpp
    - libtorch
    - cudatoolkit
    - tbb-devel

    - hdf5
    - librdkafka
    - inih
    - curl
    - nlohmann_json
    - tomlplusplus
    - libxml2
    - yaml-cpp

  run:
    - root
    - minio-cpp=latest
    - libdate-tz
    - libarchive
    - onnxruntime-cpp
    - libtorch
    - tbb-devel

    - hdf5
    - librdkafka
    - inih
    - curl
    - nlohmann_json
    - tomlplusplus
    - libxml2
    - yaml-cpp

about:
  home: "https://git.ligo.org/kagra/libraries-addons/root/root-plus"
  license: "GPL-3.0"
  summary: "ROOT+ for Tensor Calculation & Advanced Signal Processing"
  description: |
    ROOT+ is an Open-Source library implementing complex tensor calculation, advanced signal processing. It can be used for scientific Machine Learning developments in C/C++"

extra:
  recipe-maintainers:
    - meiyasan
